// Generated by gen-tool
// DO NOT EDIT!



export enum Color {

	 yellow = 1 ,

	 blue = 2 ,

	 red = 3 ,

	 green = 4 ,

}



export enum Quality {

	 yellow = 1 ,

	 blue = 2 ,

	 red = 3 ,

	 green = 4 ,

}




export class class0 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

}



export class class1 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class0> ;

}



export class class2 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class1> ;

}



export class class3 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class2> ;

}



export class class4 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class3> ;

}



export class class5 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class4> ;

}



export class class6 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class5> ;

}



export class class7 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class6> ;

}



export class class8 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class7> ;

}



export class class9 {

	public field1 : number ;

	public field2 : Array<number> ;

	public field3 : number ;

	public field4 : Array<number> ;

	public field5 : boolean ;

	public field6 : Array<string> ;

	public field7 : Array<class8> ;

}



