// Generated by gen-tool
// DO NOT EDIT!
package message

type Color int32

const (
	Color_yellow Color = 1

	Color_blue Color = 2

	Color_red Color = 3

	Color_green Color = 4
)

type Quality int32

const (
	Quality_yellow Quality = 1

	Quality_blue Quality = 2

	Quality_red Quality = 3

	Quality_green Quality = 4
)

type Class0 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`
}

type Class1 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class0 `json:"field7"`
}

type Class2 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class1 `json:"field7"`
}

type Class3 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class2 `json:"field7"`
}

type Class4 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class3 `json:"field7"`
}

type Class5 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class4 `json:"field7"`
}

type Class6 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class5 `json:"field7"`
}

type Class7 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class6 `json:"field7"`
}

type Class8 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class7 `json:"field7"`
}

type Class9 struct {
	Field1 int32 `json:"field1"`

	Field2 []int64 `json:"field2"`

	Field3 float32 `json:"field3"`

	Field4 []float64 `json:"field4"`

	Field5 bool `json:"field5"`

	Field6 []string `json:"field6"`

	Field7 []*Class8 `json:"field7"`
}
